### ISSUE TITLE
changement de nom pour le repo

### ISSUE THREAD

**Issue by strainel** [139bercy/decp-valorisation#1]
decp-projet ce n'est pas très clair.
je propose :
- decp-repair
- decp-refection
- decp-augmenté
- decp-vr
- decp-hd
...

**Comment by Lucas-GEFFARD** [comment]
decp-augmenté me semble un bon choix
Sinon, dans le même style il y aurait aussi : decp-revalorisé

**Comment by strainel** [comment]
Lucas je ne suis pas sûr que ce soit de la valorisation, on est plutôt sûr de la mise en qualité. Un peu comme on restaure un film abîmé pour avoir une qualité HD.

**Comment by Lucas-GEFFARD** [comment]
L'enrichissement des données via des sources externes/web scraping est une valeur ajoutée à ce jeu de données. Lors d'une restauration il n'y a pas d'éléments ajoutés, juste une amélioration de la qualité. Néanmoins, je peux comprendre ce point de vue.
